// User actions
export const USER_LOGOUT = `AUTH@USER_LOGOUT`;
export const USER_LOGIN = `AUTH@USER_LOGIN`;

// Search field actions
export const SET_SEARCH_FIELD_VALUE = `SEARCH_FIELD@SET_VALUE`;
/***
export const SELECT_GRID_ID = `INPUT@SELECT_GRID_ID`;
export const SET_GRID_ID_IS_PINNED = `INPUT@SET_GRID_ID_IS_PINNED`;
export const SET_HOVERED_GRID_ID = `INPUT@SET_HOVERED_GRID_ID`;
export const SET_BOUNDING_BOX_SELECTED = `INPUT@SET_BOUNDING_BOX_SELECTED`;
***/

// Query actions
export const SET_INSTITUTION_YEAR_SEARCH_RESULT = `QUERY@SET_INSTITUTION_YEAR_SEARCH_RESULT`;
export const SET_DOI_SEARCH_RESULT = `QUERY@SET_DOI_SEARCH_RESULT`;

// Map actions
export const SET_OR_TOGGLE_MAP_SELECTED_GRID_ID = `MAP@SET_OR_TOGGLE_SELECTED_GRID_ID`;
export const SET_MAP_PICKED_GRID_ID = `MAP@SET_PICKED_GRID_ID`;
export const SET_MAP_BOUNDS = `MAP@SET_BOUNDS`;
export const SET_MAP_ZOOM = `MAP@SET_ZOOM`;

// Timeline actions
export const SET_TIMELINE_SELECTION_START = `TIMELINE@SET_SELECTION_START`;
export const SET_TIMELINE_SELECTION_END = `TIMELINE@SET_SELECTION_END`;
export const SET_TIMELINE_YEAR_FOCUS = `TIMELINE@SET_YEAR_FOCUS`;

// Year slider actions
export const SET_YEAR_SLIDER_SELECTION_START = `YEAR_SLIDER@SET_SELECTION_START`;
export const SET_YEAR_SLIDER_SELECTION_END = `YEAR_SLIDER@SET_SELECTION_END`;
